### ISSUE TITLE
Chore: 보스의 원거리 공격을 맞으면 목숨 1개 차감

### ISSUE THREAD

**Issue by wndghh** [HyeonjungYun/SaveTheEarthGame#44]
## Chore: 보스의 원거리 공격을 맞으면 목숨 1개 차감
- 보스의 공격을 맞았을 때 바로 사망 -> 목숨 1개 차감으로 변경

**Comment by HyeonjungYun** [comment]
- 보스가 뿌리는 구체 피격 범위가 너무 넓어요

**Comment by wndghh** [comment]
수정하였습니다.
