### ISSUE TITLE
Add: 게임 내 아이템 추가

### ISSUE THREAD

**Issue by HyeonjungYun** [HyeonjungYun/SaveTheEarthGame#9]
# 게임 내 아이템 추가
1. 공격력 상승 아이템 추가
- 아이템 먹을 때마다 공격력이 상승하는 아이템 구현 필요
- 아이템은 운석과 동일 하게 하늘에서 랜덤하게 떨어지도록 구현
2. 스피드 상승 아이템 추가
- 아이템 먹을 때마다 공격력이 상승하는 아이템 구현 필요
- 아이템은 운석과 동일 하게 하늘에서 랜덤하게 떨어지도록 구현

**Comment by andsosallycanwait** [comment]
해당 기능 추가 및 pull request 완료
